services:
  db:
    image: postgres:16
    container_name: chinook-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./sql/Chinook_PostgreSql.sql:/docker-entrypoint-initdb.d/01_chinook.sql
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: